### ISSUE TITLE
automatic generation of swagger API docu

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#100]
As a developer I want save time and have my IDE / the build process automatically generate the swagger documentation of the REST API from the comments in the code. **Find out how to achieve this**

**Comment by tommartensen** [comment]
Just had a quick Google and this seemed quite promising: https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup-1.5

**Comment by janwestphal306** [comment]
Included with commit #145
