### ISSUE TITLE
Email Send Tasks

### ISSUE THREAD

**Issue by tommartensen** [bptlab/chimera#104]
There are some issues around EmailTasks. 
It seems that the values that you set in Chimera are not persisted in the database, which leads to invalid email subject, message, ... in the activity.

```
mysql> select * from EMAILCONFIGURATION;
+------+---------+----------------------+------------------+---------+
| DBID | MESSAGE | RECEIVEREMAILADDRESS | SENDEMAILADDRESS | SUBJECT |
+------+---------+----------------------+------------------+---------+
|  111 |         |                      |                  |         |
|  138 |         |                      |                  |         |
+------+---------+----------------------+------------------+---------+
2 rows in set (0.00 sec)

mysql> select * from EMAILACTIVITY;
+------+-------------------------+
| DBID | EMAILCONFIGURATION_DBID |
+------+-------------------------+
|  110 |                     111 |
|  137 |                     138 |
+------+-------------------------+
2 rows in set (0.00 sec)
```

This is blocking the Bookshelf project. It came up, when I started to work on https://github.com/bptlab/bookshelf-docs/issues/16. 
You can continue to work in https://github.com/bptlab/chimera/pull/103

**Comment by Tobias314** [comment]
My last commit should fix the EmailConfiguration persistence problems.
If not feel free to make a new issue with a detailed description of the situation and CaseModel where the problem occurs.

**Comment by tommartensen** [comment]
Thanks for the fast help, you solved the issue.
