### ISSUE TITLE
make credentials for email task configurable

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#105]
The credentials used for the email task should be configurable in the same way like the other properties, so that it works in a Docker deployment environment.
- adapt `config.properties.tpl` to use env variables
- set these env variables in `host.env` file in bpt-docker-zoo

**Comment by tommartensen** [comment]
This is already solved (and tested as far as it works) in #103 . Now #104 should be fixed, where it seems like the `EmailConfiguration` is not set correctly.

**Comment by tommartensen** [comment]
All dangling issues resolved. Needs re-deploy.
