### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by janwestphal306** [bptlab/chimera#107]
According to [Jenkins](https://bpt-lab.org/jenkins) there are a lot of failing tests.
Those tests should be reworked.

**Comment by marhew** [comment]
**Failing tests block the release of 1.4 milestone**
Let us fix them!

**Comment by janwestphal306** [comment]
The majority of the tests is fixed. The remaining 2 that fail, seem to have a problem with the property loader.

**Comment by janwestphal306** [comment]
@marhew On my machine they are working.

**Comment by marhew** [comment]
I fixed the usage of the test database in Jenkins. Still, 5 tests are failing and 4 produce an error: https://bpt-lab.org/jenkins/view/all/job/ChimeraDev/lastBuild/testReport/
These are the same tests that fail for me locally. @janwestphal306 Can you figure out if this is a configuration error and how we can fix it?
