### ISSUE TITLE
Start-Message-Event does not register query in Unicorn

### ISSUE THREAD

**Issue by julianweise** [bptlab/chimera#119]
Using a `StartEvent` of Type `MessageCatch` does not work for process fragments deployed to Chimera. Queries do not get registered in Unicorn. Workaround is to use an empty Start-Event and directly afterwards an Intermediate-Event of Type `MessageCatch`.
Nevertheless, this is neither a clean solution nor the point of the notation (BPMN)

**Comment by janwestphal306** [comment]
StartEvent of type MessageCatch are currently not supported. The clean solution I think of is using the `case start trigger` or does this not apply to your usecase?

**Comment by tommartensen** [comment]
We want it to start to a fragment, so a `case start trigger` is not applicable. When is this going to be implemented?

**Comment by janwestphal306** [comment]
https://bpt-lab.org/gryphon-dev/#/scenario/5a5b387bf9f582002e3d75db?_k=yjdoj0
