### ISSUE TITLE
test whether email tasks work

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#12]
As a case worker I want to model automatic tasks that send emails to some recipients given by a process variable.

In BP14 Chimera already supported email tasks. These tasks had to be configured in the Frontend by defining a text template and giving the email adress of the receiver. The template could contain process variables. This configuration is still there (in the left navigation menu: Admin-> Mail Configuration), however, the feature is not tested. **Find out whether this functionality still works, and if not, why**

**Comment by Tobias314** [comment]
Yes now it works.
