### ISSUE TITLE
wrong URLs for Unicorn & Chimea in properties file

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#176]
The default URLs of Chimera and Unicorn (properties `unicorn.url` and `chimera.url`) are `localhost:8080`. However, registering queries with that URL (or sending back notifications to Chimera) fails with error `vacuous schema part`, thrown by the http-library. The **solution** is simple: just **add `http` as prefix to the URLs**.

This needs to be changed in the `pom.xml`, where properties are set.

**Comment by janwestphal306** [comment]
Fixed by #181
