### ISSUE TITLE
New type of task to be able to copy attributes from one data object to another

### ISSUE THREAD

**Issue by mlichtblau** [bptlab/chimera#177]
### User story

As a caseworker I would like to automatically copy attributes within a task from one data object to another in order exchange information between data classes.
This would improve my workflow in the following usecases:

- After receiving data as a message about an existing data object I want to save this data in the original object.
- I combine two data objects into a new one containing information from both of the original objects.

### Feature explanation

- Similar to the existing 'JSON Path' Text Input, there should be a 'Attribute Path' Text Input that allows the case worker to input variables process variables from which the information should be copied
- This enables Chimera users to perform more tasks automatically instead of having to type all the attributes for the output objects by hand
- Changes will have to be made in the frontend to allow users to set process variables for the output data attributes.
- We also need a new task type or change the behaviour to perform this copy automatically
- We also need to change the backend to perform the copy process

### Benefits for users

- Allows more automation by removing unnecessary interaction with the user

**Comment by janwestphal306** [comment]
Is it necessary to create a new activity type for this?
Wouldn't it be helpful for all activity and events to have this feature of transferring the value of one data attribute of one data object in the input set to another data attribute in another data object in the output set?
