### ISSUE TITLE
execute fragments with data pre-conditions

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#39]
As a case worker I want that fragments with data pre-conditions are only enabled when the condition is fulfilled, i.e. when the specified data objects are available in the specified state. The execution logic of the engine needs to check whether the pre-conditions of a fragment are fulfilled and only then enable the first activity of that fragment. If the pre-condition becomes unsatisfied **before the first activity instance begins**, i.e. the fragment instance is not yet in active, then the fragment instance is disabled again, as well as its activity instances. However, if the fragment instance is active and then the pre-condition becomes unsatisfied, the fragment instance continues execution, but no new fragment instances can be started.

**Acceptance criteria**
- case model with fragment pre-conditions exist to test this behavior

- [x] Fragment Instance state: created, enabled, disabled, active
- [x] corellation between fragment instance state and control instance state
- [x] make sure only activities of enabled & active fragment instances are shown
- [x] event instances shall be affected of preconditions
- [x] write an acceptance test for activity instances

**Comment by janwestphal306** [comment]
How does the fragment precondition affect the first control node instances if they are event instances?

**Comment by janwestphal306** [comment]
Receive events will not terminate if the fragment instance is not enabled.
