### ISSUE TITLE
prevent attribute changes when DO is not in output set

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#45]
As a modeler I want to distinguish between read-only and read-write access to data objects. In the current implementation a user can change the attribute values of a data object which appears only in the input set. This is undesired! Attributes values should only be editable if the DO appears in the output set.
*This probably needs changes in the Frontend as well*.

**Acceptance Criteria**:
- Test case model exists to demonstrate intended behavior

**Comment by janwestphal306** [comment]
As expected the bug is fixed in the refactored version.
