### ISSUE TITLE
Persisting values of DataAttributeInstances

### ISSUE THREAD

**Issue by Tobias314** [bptlab/chimera#65]
Because the `value` instance variable of DataAttributeInstance is of type Object instead of a "primitive" type, it is not persisted at the moment. This has to be changed because values of DataAttributeInstances are very important and therefore should be persisted.

**Comment by marhew** [comment]
Find out the best practice for persisting values that can be of different types. Persisting it as a String representation might be the simplest way.

**Comment by marhew** [comment]
Attribute values are now declared as `Serializable` and stored in the database as binary blobs.
