### ISSUE TITLE
handle case termination in backend

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#73]
As a result of clicking the "Terminate Case" in the Frontend the case should be set to state `terminated`. When terminating, Chimera checks again, if something happened in the mean time, e.g. an event was received from Unicorn, or some other user terminated an activity that changed a DO state. 
No new activities may be started, running activities can not be terminated but are instead skipped. Chimera needs to un-subscribe existing event queries, events that are received after terminating the case are ignored (need to consider race conditions). The event dispatcher API needs to check if the case is terminated.
The frontend displays terminated cases differently (greyed out).

**Comment by tommartensen** [comment]
Got some follow-up questions/issues that arose when I tried to terminate a case: 

After clicking on "Terminate", the case is still open (not closed) in the frontend (Overview of Cases) and I can still click the button to terminate again. 
*Is that intended?*

When I restart the server, the case is terminated (just as I expect it).

**Comment by marhew** [comment]
The backend de-registers event subscriptions and skips all tasks (after I reloaded the case view, there where no enabled activities). However, the frontend should at least have 'terminated=yes' in the cases list. But the REST call to the backend asking for instances (`https://bpt-lab.org/chimera-dev/api/interface/v2/scenario/adc93cabcc104ee98287e92b498aac5d/instance/`) states that no instance is terminated.
**Needs further work**

**Comment by tommartensen** [comment]
Thanks for the clarification!

**Comment by friedow** [comment]
According to best practices for rest API's, I would expect `/instances` to return all instances, having an attribute, indicating whether they are terminated.
Furthermore I would expect the endpoint to have filtering capabilities (e.G. `/instances?terminated=false`), in  to retrieve running instances. Filtering, sorting, field selection and paging for API's is described in [point 7 of this article](https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/).

**Comment by marhew** [comment]
@janwestphal306 reported that this bug is related to how the ExecutionService manages the lists of cases.

**Comment by janwestphal306** [comment]
#142
