### ISSUE TITLE
testing in Chimera

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#8]
So far, testing in Chimera includes only unit testing. The problem with this is that most functions you want to unit test operate on the database. This means you have to manipulate the database for testing. Right now, the unit tests take so long, that I build Chimera with `-DskipTests`. **We should make the unit tests useful.**

We should go beyond unit testing and **test that cases are executed as expected**.  For example, I want to test that a data-based XOR-Gateway enables those succeeding activities for which the condition on the control flow arc evaluates to true. 

Further, we should **test the API**. What happens when I try to begin an activity that is already running, or one which is not data-flow-enabled? Also, **testing the performance** is a good idea, how many requests can the engine handle, where is it spending the most time (preliminary tests in the BA thesis of @jaSunny indicated that majority of time is spend with database operations).

**Comment by jaSunny** [comment]
:+1:

**Comment by marhew** [comment]
Naming for test cases is required. Find out how to organize the structure of testresources.

**Comment by marhew** [comment]
Create a wiki page to document how testing in Chimera 1.3 works, i.e. how new tests should be written.
