### ISSUE TITLE
Unable to deploy fragments from Gryphon to Chimera

### ISSUE THREAD

**Issue by julianweise** [bptlab/chimera#81]
We modeled several fragments in one case in Gryphon and tried to deploy them to Unicorn.

**Expected behavior:**
All fragments are completely deployed to Chimera under its parent case and are ready to execute.

**Actual behavior:**
The deployment process fails (in Gryphon and via REST-Call (Postman) with the exported JSON file.
Gryphon returns the following error message:
```
[
    {
        "text": "there is at least one Sequence Flow Association which ins't attached to a Controlnode on both sides - id: SequenceFlow_1tgb198",
        "type": "danger"
    }
]
```
We tried to remodel the affected sequence-flow and also removed/recreated the affected fragment but without success.

Additionally, we tried several ways to bypass this error:

- Using bpt chimera
- Using bpt/book-shelf chimera
- Using a locally (via docker) deployed chimera

[Gryphon case](https://github.com/bptlab/chimera/files/2064869/5b0da58703b52f003d9ecba5.json.zip) attached to his issue.
This might also be a Gryphon bug.

**Comment by marhew** [comment]
I have the strong suspicion that this is caused by manual tasks. They are not parsed and I assume this is the reason why the SequenceFlow is "not connected". **Workaround**: Do not use any fancy modeling constructs, only plain and service tasks are supported.

**Comment by marhew** [comment]
Extend parser to treat manual and user tasks just like plain tasks.

**Comment by julianweise** [comment]
Could you please deploy it to bookshelf/chimera as well?

**Comment by janwestphal306** [comment]
With merge #92 on dev they get parsed but for the moment handled as human tasks.
