### ISSUE TITLE
support for authentication headers

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#86]
As a case modeler I want to use web services that require a form of header authentication (instead of including the auth token in the URI). bptlab/gryphon#28 adds a 'headers' property for web service tasks (`bpmn:serviceTask` in the exported XML). This property has to be parsed, stored in the `WebServiceTask`, and used during execution to set the specified headers in the web service call.

The usual variable replacement should be used, to facilitate that things like username and password are stored in data objects.

**Comment by tommartensen** [comment]
Blocked by https://github.com/bptlab/chimera/issues/83
