### ISSUE TITLE
deletion of case models fails (sometimes...)

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#88]
Deleting case models in the frontend does not work. However, for some case models it seems to work. It might be that you need cases for deletion to work. Please have a look.

**Comment by marhew** [comment]
Still it sometimes failes to delete case models from the database. Might be connected with the existence of cases.
Try the following:
- load case models in InitAndDestroy when the container is started
- try deleting with persistence disabled
- save cases into database when they are created

**Comment by marhew** [comment]
**blocking** milestone 1.4

**Comment by marhew** [comment]
@Tobias314 reported that this issue is *probably not caused* by concurrency and race conditions. After deletion, the case model was deleted from the database, however, after the next persistence operation (periodically every 10 seconds) it was there again. It is likely, that the case model is still being referenced by some map and hence written anew.

**Comment by janwestphal306** [comment]
I would close this issue for now because this problem seems to be solved.
