### ISSUE TITLE
API return values of /casestart are lists

### ISSUE THREAD

**Issue by friedow** [bptlab/chimera#94]
The newly created API endpoint /casestart on scenario instances returns lists of values instead of plain strings, as shown in Image 1.

- [ ] Correct return value
- [ ] Add endpoint documentation

![Image 1](https://user-images.githubusercontent.com/17351844/41396950-d594e986-6fb2-11e8-9833-82c2d30d08bb.png)

**Comment by tommartensen** [comment]
So instead you expect: 
```json
[
  {
    "id": "a....f",
    "plan": "Select * from TestA"
  }
]
```
?

**Comment by tommartensen** [comment]
@friedow https://github.com/bptlab/chimera/blob/dev/src/main/java/de/hpi/bpt/chimera/rest/EventRestService.java#L122 
The root cause is that the values are appended and not put into the JSON. 
I can fix that tomorrow, but would need some data to test it on.

**Comment by tommartensen** [comment]
@friedow This is merged. Documentation will be auto-generated in #100 .
