### ISSUE TITLE
Documentation of API endpoint activity/begin body is inconsistent

### ISSUE THREAD

**Issue by friedow** [bptlab/chimera#96]
According to the swagger documentation the API route
POST /scenario/{scenarioId}/instance/{instanceId}/activityinstace/{activityInstanceId}/begin
takes an object like:
`{
  "dataobjects": [
    0
  ]
}`
Instead the API endpoint takes just the Array of dataobject id's as an input, which is fine, but inconsistent with it's documentation. The documentation of the required body should look like:
`[
    dataobjectId
]`

**Comment by marhew** [comment]
Related to #100 
Part of #99

**Comment by marhew** [comment]
Not relevant anymore since API is moved to version 3
