### ISSUE TITLE
activity/terminate resets the state of an dataobject

### ISSUE THREAD

**Issue by friedow** [bptlab/chimera#97]
## Description
If the terminate endpoint on activities is called from somewhere else, then the chimera frontend, a dataobject, changing its state on activity termination, is resetted to its initial state. Interestingly, only the /dataobject endpoint has the dataobject in it's resetted state. Everything else in chimera behaves, as if the dataobject had changed its state.

This is a blocking issue for the PMB Seminar.

## Exemplary Case
https://bpt-lab.org/bpt-bookshelf/chimera/#/scenario/0e823004500c4486a91d2e8340ebdeb5/instance/b8344808d4794c7a82020f0499dac16a/

### Case Fragment
![image](https://user-images.githubusercontent.com/17351844/41440107-9b43f74c-702d-11e8-8af1-1abfdd86d70f.png)

### Activity Log
As you can see, the activity ran and terminated correctly.
![image](https://user-images.githubusercontent.com/17351844/41440133-bb2d5a6c-702d-11e8-977d-6b8b4454e48f.png)

### Dataobject Log
According to the DO log, the dataobject changed it's state correctly.
![image](https://user-images.githubusercontent.com/17351844/41440158-d4bcca58-702d-11e8-9c8f-def32cb93bbd.png)

### Dataobject State according to the /dataobject endpoint
The /dataobject endpoint gives a wrong value for the dataobjects state.
![image](https://user-images.githubusercontent.com/17351844/41440231-109e88ea-702e-11e8-8210-1e797375c26a.png)

**Comment by tommartensen** [comment]
Is the actual API serving the wrong response for the data object or is it just shown wrong in the Chimera UI? There is a similar issue with closed fragments in that view.

**Comment by tommartensen** [comment]
@friedow Would you also provide the POST Body of your request for debugging? Thanks!

**Comment by tommartensen** [comment]
We were not able to reproduce this issue anymore. It's a miracle!
